# Generated by Django 4.2.16 on 2024-12-04 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_outlet', '0008_country_alter_address_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='published_countries',
            field=models.ManyToManyField(related_name='books', to='book_outlet.country'),
        ),
    ]
